name: tests

on: [pull_request]

jobs:
    tests:
        runs-on: ubuntu@latest

        env:
            NODE_ENV: test
            MONGO_DB_CONNSTR: ${{ vars.MONGO_DB_CONNSTR }}


        strategy:
            matrix:
                node-version: [20.x]
        

        steps:
            - name: checkout and run tests
              uses: actions/checkout@v4
            - run: npm i
            - run: npm test
              env:
                  CI: true
                  MONGO_DB_CONNSTR: ${{ vars.MONGO_DB_CONNSTR }}
            - run: kill $(jobs -p)



