name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
        # run: npm ci

      - name: Start application
        run: npm start &
        env:
          MONGO_DB_CONNSTR: ${{ secrets.MONGO_DB_CONNSTR }}

      - name: Run tests
        run: npm test
        env:
          CI: true
          MONGO_DB_CONNSTR: ${{ secrets.MONGO_DB_CONNSTR }}

      - name: Kill background processes
        run: kill $(jobs -p)
